plugins {
    id 'application'
}

sourceSets {
    main {
        java.srcDirs = ['src']
        resources.srcDirs = []
    }
    test {
        java.srcDirs = []
        resources.srcDirs = []
    }
}

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:${gdxVersion}"
    runtimeOnly "com.badlogicgames.gdx:gdx-platform:${gdxVersion}:natives-desktop"
}

application {
    mainClass = 'com.duddlejump.desktop.DesktopLauncher'
}

tasks.named('run').configure {
    workingDir = rootProject.file('assets')

    if (System.getProperty('os.name').toLowerCase().contains('mac')) {
        jvmArgs += '-XstartOnFirstThread'
    }
}
